---
- hosts: all
  become: yes

  vars_files:
    - ../vars/user_list.yml
    - ../vars/secret.yml

  tasks:

    - name: Create webserver users
      block:

        - name: Create webserver users
          user:
            name: "{{ item.username }}"
            uid: "{{ item.uid }}"
            groups: wheel
            shell: '/bin/bash'
            update_password: on_create
            password: "{{ user_password | password_hash('sha512') }}"
          with_items: "{{ users }}"

        - name: Create .ssh folder for webserver users
          file:
            path: "/home/{{ item.username }}/.ssh"
            state: directory
            owner: "{{ item.username }}"
            group: "{{ item.username }}"
            mode: '0700'
          with_items: "{{ users }}"

        - name: Upload SSH private key for webserver users
          copy:
            src: ../webservers_rsa
            dest: "/home/{{ item.username }}/.ssh/id_rsa"
            owner: "{{ item.username }}"
            group: "{{ item.username }}"
            mode: '0700'
          with_items: "{{ users }}"

        - name: Set authorized key for webserver users
          authorized_key:
            user: "{{ item.username }}"
            state: present
            key: "{{ lookup('file', '/home/automation/plays/webservers_rsa.pub') }}"
          with_items: "{{ users }}"

      when:
        - item.uid | string | regex_search('^1') and 'webservers' in group_names


    - name: Create database users
      block:

        - name: Create database users
          user:
            name: "{{ item.username }}"
            uid: "{{ item.uid }}"
            groups: wheel
            shell: '/bin/bash'
            password: "{{ database_password | password_hash('sha512') }}"
            update_password: on_create
          with_items: "{{ users }}"

        - name: Create .ssh folder for database users
          file:
            path: "/home/{{ item.username }}/.ssh"
            state: directory
            owner: "{{ item.username }}"
            group: "{{ item.username }}"
            mode: '0700'
          with_items: "{{ users }}"

        - name: Upload SSH private key for database users
          copy:
            src: ../database_rsa
            dest: "/home/{{ item.username }}/.ssh/id_rsa"
            owner: "{{ item.username }}"
            group: "{{ item.username }}"
            mode: '0700'
          with_items: "{{ users }}"

        - name: Set authorized key for database users
          authorized_key:
            user: "{{ item.username }}"
            state: present
            key: "{{ lookup('file', '/home/automation/plays/database_rsa.pub') }}"
          with_items: "{{ users }}"

      when:
        - item.uid | string | regex_search('^2') and 'database' in group_names

